@startuml mybus
class Onibus{
    -numero:str
    -placa:str
    -status:boolean
}
class Usuario{
    -nome:str
    -cpf:str
    -telefone:str
    -papel: str

}
class Linha{
    -nome:str
    -numero:str
}
class Rota{
    -trajetoSentido:str
}


class Ponto{
    -latitude:float
    -longitude:float
    -descricao:str

}

class Cronograma{
    tipoDia: str
}

class UserLinha{
    -quantidadeUso:int
    -favorito:boolean
}

class Horario {
    -HoraMinuto: str

}

Linha "0..1" -- "0..*" Onibus
Rota "1..*" -- "1..1"Linha
Ponto "1..*" -- "1..1" Rota
Linha "1..1" -- "1..*" Cronograma
Cronograma "1..*" -- "1..1"Horario
Usuario "1..1" -- "0..*"UserLinha
Linha "1..1" -- "0..*" UserLinha





@enduml