@startuml mybus
class Onibus{
    -numero:str
    -placa:str
    -status:boolean
}
class Usuario{
    -nome:str
    -cpf:str
    -telefone:str
    -papel: str
    -status: str
}
class Linha{
    -nome:str
    -numero:str
}

class Rota{
    -trajetoSentido:str
    -coordenadas:list
    -marcacao:list
}


class Cronograma{
    tipoDia: str
    horarios: list
}

class UserLinha{
    -quantidadeUso:int
    -favorito:boolean
}

Linha "0..1" -- "0..*" Onibus
Rota "1..*" -- "1..1" Linha
Linha "1..1" -- "1..*" Cronograma
Usuario "1..1" -- "0..*"UserLinha
Linha "1..1" -- "0..*" UserLinha





@enduml