@startuml sistema_de_locacao_filmes

left to right direction

actor Administrador
actor Usuário
actor "Sistema de rotas"

rectangle "Sistema MyBus" {

    (Visualizar Rotas)
    (Traçar Rotas)
    (Gerenciar Rotas)
    (Gerenciar Ônibus)
    (Registrar Viagem)
    

    Usuário -- (Visualizar Rotas)
    Administrador -- (Gerenciar Rotas)
    Administrador -- (Gerenciar Ônibus)
    (Traçar Rotas) -- "Sistema de rotas"
    
    
    (Visualizar Rotas) <.. (Registrar Viagem) : <<extend>>
    (Gerenciar Rotas) <.. (Traçar Rotas) : <<extend>>

}

@enduml